library(shiny)
library(leaflet)
library(leaflet.esri)
library(shinydashboard)
library(dplyr)
library(tidyverse)
library(magrittr)
library(shinyBS)
library(msm)
library(shinyjs)
library(shinyWidgets)
library(data.table)
library(DT)
library(zip)
library(RColorBrewer)
library(pracma)
library(rcmdcheck)
library(sp)
library(sf)
library(rgdal)
library(geosphere)
library(readr)
library(rgeos)
# library(rhandsontable)
library(htmltools)
library(rmarkdown)
library(fs)
library(latexpdf)
library(Hmisc)
library(tinytex)
# library(gmailr)
library(ipc)
library(future)
library(promises)
plan(multiprocess)

#1/2 degree grid with 0 low confidence and 1 high confidence range for calcs 
# FRom CF. These seem to be the same for PIPL, ROST, REKN
# conf_grid_BOEM_halfdeg <- rgdal::readOGR("data", "BOEM_halfdeg_grid_latlon_2021")
# high_conf_grid <- conf_grid_BOEM_halfdeg[which(conf_grid_BOEM_halfdeg$PIPL==0),]
# high_conf_grid_polys <- high_conf_grid@polygons
# sp::spplot(conf_grid_BOEM_halfdeg)
