library(shiny)
library(shinyBS)
library(shinydashboard)
library(dplyr)
library(tidyverse)
library(magrittr)
library(msm)
library(shinyjs)
library(shinyWidgets)
library(data.table)
library(DT)
library(zip)
library(RColorBrewer)
library(pracma)
library(rcmdcheck)
library(sp)
library(sf)
library(rgdal)
library(geosphere)
library(readr)
library(rgeos)
# library(rhandsontable)
library(htmltools)
library(rmarkdown)
library(fs)
library(latexpdf)
library(Hmisc)
library(tinytex)
# library(gmailr)
library(ipc)
library(leaflet)
library(leaflet.esri)
library(ggplot2)
library(future)
library(promises)
plan(multiprocess)


#load the species movement model mean monthly probability data
#generate all species data
data_dir <- "P:/SCRAM/BRI/SCRAM_shiny/data"
for (species in c("Red_Knot", "Piping_Plover", "Roseate_Tern")){
  data_layer <-  paste0(species, "_monthly_prob_BOEM_half_deg")
  load(file.path(data_dir, paste0(species, "_monthly_prob_BOEM_half_deg.RData")))
  assign(data_layer, spp_monthly_prob_BOEM_half_deg)
}
rm(spp_monthly_prob_BOEM_half_deg)
